<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\RamT.Domain\RamT.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Models\DTO\" />
    <Folder Include="Interfaces\" />
    <Folder Include="Services\" />
  </ItemGroup>

</Project>
